### PR TITLE
Revert "Update pyarrow requirement from <3.1.0,>=3.0.0 to >=3.0.0,<4.1.0

### PR DESCRIPTION
**Pull request by sfc-gh-abhatnagar**
This reverts commit c3bbcb595cec630f0692b01dad3cfc38dd7e30a7.

### CODE REVIEW

**Review by sfc-gh-cshi — APPROVED** [review]

**Comment by xhochy** [comment]
What is the reason for this?

**Comment by sfc-gh-abhatnagar** [comment]
> What is the reason for this?

This is failing on our MacOS build machine . This is blocking our  scheduled release next week , we will upgrade OS version on our Mac build machine after release and commit this change again after that .

**Comment by sfc-gh-mkeller** [comment]
> What is the reason for this?

We might have found an issue in the latest `pyarrow` releases. This is our setup on our Jenkins worker:
```console
$ uname -a
Darwin imac.local 17.7.0 Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64 x86_64
$ python --version --version
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
$ pip list
Package    Version
---------- -------
Cython     0.29.23
numpy      1.19.5
pip        21.1.2
pyarrow    4.0.0
setuptools 57.0.0
wheel      0.36.2
```

We get the following error:
```console
$ python -c "import pyarrow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Shared/Jenkins/Home/workspace/BuildPyConnector-Mac/venv-36/lib/python3.6/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
ImportError: dlopen(/Users/Shared/Jenkins/Home/workspace/BuildPyConnector-Mac/venv-36/lib/python3.6/site-packages/pyarrow/lib.cpython-36m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/Shared/Jenkins/Home/workspace/BuildPyConnector-Mac/venv-36/lib/python3.6/site-packages/pyarrow/libarrow.400.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/Shared/Jenkins/Home/workspace/BuildPyConnector-Mac/venv-36/lib/python3.6/site-packages/pyarrow/libarrow.400.dylib
```

Do you know what could cause this issue @xhochy ? I was gonna open an issue with Arrow.

**Comment by xhochy** [comment]
Yes, please open an issue. The error tells us that it requires a 10.15+ system. We probably need to use a different SDK to get this to work correctly.

**Comment by sfc-gh-mkeller** [comment]
Created: https://issues.apache.org/jira/browse/ARROW-13108

**Pull request merged**
