### PR TITLE
SNOW-215481 fix string formatting in exceptions

### PR DESCRIPTION
**Pull request by jameslamb**
Similar to #393 , this proposes fixing a small bug caught with `pylint`. See that PR for the command I ran.

```text
src/snowflake/connector/ocsp_snowflake.py:415:16: W0715: Exception arguments suggest string formatting might be intended (raising-format-tuple)
src/snowflake/connector/remote_storage_util.py:150:16: W0715: Exception arguments suggest string formatting might be intended (raising-format-tuple)
src/snowflake/connector/remote_storage_util.py:248:16: W0715: Exception arguments suggest string formatting might be intended (raising-format-tuple)
```

A few exceptions in this library's Python code have a small mistake in the way they're handling string formatting. The code and screenshot below illustrate the issue:

```python
thing = "abc"

# will raise an exception with a tuple and the format string
raise Exception(
    "Unknown Error in downloading a file: %s",
    thing
)

# will raise an exception with the intended message
raise Exception(
    "Unknown Error in downloading a file: {}".format(thing)
)
```

image

I observed this behavior on Python version 3.7.6.

This PR proposes replacing `%s` with `.format()`, which will work in all versions of Python.

### How does this PR improve `snowflake-connector-python`?

This makes the messages in these exceptions slightly more accurate, removing stuff that might be misleading (like the presence of format strings like `%s`).

Thanks for your time and consideration!

### CODE REVIEW

**Comment by jameslamb** [comment]
Does this need any other changes?

**Review by sfc-gh-mkeller — APPROVED** [review]
🚢 🚢

**Comment by sfc-gh-mkeller** [comment]
Closes #396

**Comment by sfc-gh-mkeller** [comment]
Merged through #396

**Pull request closed without merging**
