### PR TITLE
SNOW-240336 adding Python 3.9 support

### PR DESCRIPTION
**Pull request by sfc-gh-mkeller**
SNOW-240336
Adding support and testing for Python 3.9 for both Jenkins and GH actions.
`pyarrow` dropped releasing `manylinux1` wheels, so I did some digging and it appears as it's okay for us to do the same as well.

### CODE REVIEW

**Comment by sfc-gh-mkeller** [comment]
So `pyarrow` depends on `numpy`, but the `numpy` that our old `pyarrow` asks for doesn't compile for python 3.9. So to get this to work we need to update `pyarrow` as well.

**Comment by sfc-gh-mkeller** [comment]
It looks like `pyarrow` will support 3.9 soon: https://github.com/snowflakedb/snowflake-connector-python/issues/382#issuecomment-762450065

**Comment by sfc-gh-mkeller** [comment]
`pyarrow` dropped `manylinux1` support, this might take longer again...

**Comment by sfc-gh-mkeller** [comment]
I looked into the [original issue](https://github.com/snowflakedb/snowflake-connector-python/issues/252) why we added back `manylinux1` wheel releases.

It looks like since then AWS lambda added support for `manylinux2010` and even `manylinux2014`. See https://github.com/aws/aws-lambda-builders/blob/ae614efb788984407792ffc390df8e3cf313cf6f/aws_lambda_builders/workflows/python_pip/packager.py#L153

So in this PR I adjusted the build Docker image to be `manylinux2010`.

**Review by sfc-gh-stakeda — APPROVED** [review]
LGTM, but looks like this change is significant enough to bump up at least minor version of Python Connector and make a clear announcement in https://docs.snowflake.com/en/release-notes.html.

**Review by sfc-gh-stan — APPROVED** [review]
🚢 🚢

**Comment by idanw206** [comment]
Hey!
When will it be merged?

**Comment by sfc-gh-mkeller** [comment]
Successful Jenkins tests:

* Linux
  * 36: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector36/5033
  * 36-FIPS: https://jenkins.int.snowflakecomputing.com/job/RT-FIPS-PyConnector36/3577
  * 37: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector37/5030
  * 38: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector38/5030
  * 39: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector39/1

* Windows
  * 36: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector36-Win/172 (Hit a flaky test, I'm going squash this one test bug soon)
  * 37: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector37-Win/169
  * 38: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector38-Win/60
  * 39: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector39-Win/1
  
* Mac
  * 36: http://172.16.20.10:8080/job/RT-PyConnector36-Mac/178 (Consistently hangs on same test `test_encrypt_decrypt_file`, but I'm unable to reproduce locally and when I run the test manually on Jenkins)
  * 37: http://172.16.20.10:8080/job/RT-PyConnector37-Mac/177
  * 38: http://172.16.20.10:8080/job/RT-PyConnector38-Mac/177 (Same flaky test as Windows 36)
  * 39: http://172.16.20.10:8080/job/RT-PyConnector39-Mac/1

I know some of the GH actions failed too, but they all failed on the (newly) flaky test. I checked query history and it is because the one query spends a bunch of time being queued on the test warehouse. I'll address this test in a subsequent PR!

**Pull request merged**
