### PR TITLE
Replace runtime dependency on setuptools with modern libraries

### LINKED ISSUE #1447: SNOW-748919: Replace runtime dependency on setuptools with modern libraries
The use of `pkg_resources` that gets installed alongside setuptools is heavily discouraged now that functionality exists in the standard library and because importing that has a deleterious penalty to both start-up time and RSS memory.

### PR DESCRIPTION
**Pull request by ofek**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #1447

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   The logic to detect incompatible versions of PyArrow now uses the standard library (on Python >3.7) and the fundamental library `packaging`.

### CODE REVIEW

**Comment by ofek** [comment]
I have read the CLA Document and I hereby sign the CLA

recheck

**Comment by ofek** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ofek** [comment]
recheck

**Review by sfc-gh-mkeller — APPROVED** [review]
Thanks for the PR!

:ship: :ship:

**Pull request merged**
