### PR TITLE
Bump supported arrow version to 0.16 and add Python 3.8 support

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by keller00** [comment]
Thank you, I will get to this sometime soon!

**Comment by keller00** [comment]
I'm going to accept this, thank you!
We'll include 3.8 in the next release!

**Comment by xhochy** [comment]
If this is going to be merged why was it then closed?

**Comment by keller00** [comment]
Currently the code lives in a private repository. We just sync this repo to that.
So we manually merge PRs into that repo and then sync them back here upon release.

**Comment by xhochy** [comment]
Ah, ok. Not the best approach but at least things are OSS here. This also explains the unused Travis config. It would be nice when this was mentioned in the `README.md` or the `CONTRIBUTING.md`.

**Comment by keller00** [comment]
We are currently working on moving to this repository full-time. Stay tuned 😄

**Pull request closed without merging**
