### PR TITLE
SNOW-421731 use central copy of actions

### PR DESCRIPTION
**Pull request by sfc-gh-mmacintyre**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes SNOW-421731

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

### CODE REVIEW

**Comment by sfc-gh-mmacintyre** [comment]
recreate jira

**Comment by sfc-gh-mmacintyre** [comment]
@sfc-gh-mkeller Testing this is tricky, since all of the issue-related stuff is going to pull workflow files from the default branch, not my PR branch.  I've added the bogus extra workflow in the 2nd commit to exercise and verify the checkout and run from the gh-actions repo.  Seems to be working correctly - if you're ok with it, LMK and I'll clean this up and turn it into a full PR, then we can update the remaining repositories.

**Comment by sfc-gh-mmacintyre** [comment]
The successful run of the test action is at https://github.com/snowflakedb/snowflake-connector-python/runs/4217654917?check_suite_focus=true

**Comment by sfc-gh-mkeller** [comment]
> @sfc-gh-mkeller Testing this is tricky, since all of the issue-related stuff is going to pull workflow files from the default branch, not my PR branch. I've added the bogus extra workflow in the 2nd commit to exercise and verify the checkout and run from the gh-actions repo. Seems to be working correctly - if you're ok with it, LMK and I'll clean this up and turn it into a full PR, then we can update the remaining repositories.

I think testing this would be easier on a fork, otherwise I'm okay if you just merge things into master to test as well. I'm sure that you'll clean up your mistakes quickly 😄

**Review by sfc-gh-mkeller — APPROVED** [review]
🚢 🚢

**Pull request merged**
