### PR TITLE
Fixes #124 Split out aws and azure dependencies

### LINKED ISSUE #124: Optional dependencies for azure and boto?
As user not intending to use boto or azure modules, e.g. in case of using the connector for simple queries to Snowflake, is it be possible to relax the dependency requirements for these particular modules?

### PR DESCRIPTION
**Pull request by richiverse**
To install the azure plugins:

```bash
pip install --upgrade snowflake-connector-python[azure]
```

To install the aws plugins:

```bash
pip install --upgrade snowflake-connector-python[aws]
```

---
This change is [Reviewable](https://reviewable.io/reviews/snowflakedb/snowflake-connector-python/172)

### CODE REVIEW

**Comment by richiverse** [comment]
Getting 

```ImportError while loading conftest 'C:\projects\snowflake-connector-python\test\conftest.py'.
test\conftest.py:18: in <module>
    from parameters import CONNECTION_PARAMETERS
E   ModuleNotFoundError: No module named 'parameters'
``` from appveyor but I don't have those encrypted vars

**Comment by smtakeda** [comment]
This duplicates https://github.com/snowflakedb/snowflake-connector-python/issues/124

Now we are planning to have GCS... Sounds like we should do this change soon.

**Comment by borgstrom** [comment]
Is there anything we can do to help get this prioritized?

The azure packages use PEP420 style namespace packages, which are incompatible with our use of pkg_resources + pex for the way we distribute our python apps, so when we try to ship an app with the snowflake connector we can’t even import it because it implicitly depends on the azure module.

Along with splitting out the deps into extras a number of different files (`remote_storage_util.py`, `file_transfer_agent.py`, etc) will need to catch `ImportError` exceptions to handle the case when these extras are not installed.

```
>>> import snowflake.connector
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/eborgstrom/.pex/install/snowflake_connector_python-1.8.3-py2.py3-none-any.whl.be016a9669699bdb9976c773071368cc90bb99ec/snowflake_connector_python-1.8.3-py2.py3-none-any.whl/snowflake/connector/__init__.py", line 21, in <module>
    from .connection import SnowflakeConnection
  File "/Users/eborgstrom/.pex/install/snowflake_connector_python-1.8.3-py2.py3-none-any.whl.be016a9669699bdb9976c773071368cc90bb99ec/snowflake_connector_python-1.8.3-py2.py3-none-any.whl/snowflake/connector/connection.py", line 42, in <module>
    from .cursor import SnowflakeCursor, LOG_MAX_QUERY_LENGTH
  File "/Users/eborgstrom/.pex/install/snowflake_connector_python-1.8.3-py2.py3-none-any.whl.be016a9669699bdb9976c773071368cc90bb99ec/snowflake_connector_python-1.8.3-py2.py3-none-any.whl/snowflake/connector/cursor.py", line 29, in <module>
    from .file_transfer_agent import (SnowflakeFileTransferAgent)
  File "/Users/eborgstrom/.pex/install/snowflake_connector_python-1.8.3-py2.py3-none-any.whl.be016a9669699bdb9976c773071368cc90bb99ec/snowflake_connector_python-1.8.3-py2.py3-none-any.whl/snowflake/connector/file_transfer_agent.py", line 20, in <module>
    from .azure_util import SnowflakeAzureUtil
  File "/Users/eborgstrom/.pex/install/snowflake_connector_python-1.8.3-py2.py3-none-any.whl.be016a9669699bdb9976c773071368cc90bb99ec/snowflake_connector_python-1.8.3-py2.py3-none-any.whl/snowflake/connector/azure_util.py", line 8, in <module>
    from azure.common import (AzureMissingResourceHttpError, AzureHttpError)
ImportError: No module named common
```

**Comment by smtakeda** [comment]
Duplicates #124

**Pull request closed without merging**
