### PR TITLE
SNOW-628190 bumping pyarrow version

### PR DESCRIPTION
**Pull request by sfc-gh-mkeller**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes SNOW-628190

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Bumping `pyarrow` to the newest version.

### CODE REVIEW

**Comment by sfc-gh-mkeller** [comment]
It looks like `pyarrow` changed its API, so some code will need to updated

**Comment by juanjgalvez** [comment]
Hi. I'm not able to install the snowflake-connector-python on conda with Arrow 8 (conda needs to downgrade Arrow to 7). When is Arrow 8 support going to be released?

**Comment by juanjgalvez** [comment]
Hi @sfc-gh-mkeller . I noticed that the `snowflake-connector-python` package in conda forge is built against (or works with) different versions of pyarrow (currently from version 4 to 7).

This branch doesn't build with Arrow versions < 8 because of the change in `arrow_iterator.pyx`, but one way that would allow building the connector for Arrow 4-8 would be this (see diff below). I think some further changes would still be needed to select the arrow library version to link with at build time, and maybe this would require changes in the conda forge recipe too. What do you think? Hopefully this is helpful.

```diff
diff --git a/setup.py b/setup.py
index 8f64fcf..0b8f59e 100644
--- a/setup.py
+++ b/setup.py
@@ -54,6 +54,7 @@ except ImportError:

 if _ABLE_TO_COMPILE_EXTENSIONS:

+    pyarrow_version = tuple(int(x) for x in pyarrow.__version__.split("."))
     extensions = cythonize(
         [
             Extension(
@@ -61,6 +62,7 @@ if _ABLE_TO_COMPILE_EXTENSIONS:
                 sources=[os.path.join(CONNECTOR_SRC_DIR, "arrow_iterator.pyx")],
             ),
         ],
+        compile_time_env=dict(ARROW_LESS_THAN_8=pyarrow_version < (8,))
     )

     class MyBuildExt(build_ext):
diff --git a/src/snowflake/connector/arrow_iterator.pyx b/src/snowflake/connector/arrow_iterator.pyx
index 5bea793..5356633 100644
--- a/src/snowflake/connector/arrow_iterator.pyx
+++ b/src/snowflake/connector/arrow_iterator.pyx
@@ -22,7 +22,10 @@ from pyarrow.includes.libarrow cimport (
     Readable,
     Seekable,
 )
-from pyarrow.includes.libarrow_python cimport PyReadableFile
+IF ARROW_LESS_THAN_8:
+    from pyarrow.includes.libarrow cimport PyReadableFile
+ELSE:
+    from pyarrow.includes.libarrow_python cimport PyReadableFile

 from .constants import IterUnit
 from .errorcode import (
```

**Comment by sfc-gh-mkeller** [comment]
Re-opened as #1196

**Pull request closed without merging**
