### PR TITLE
SNOW-499608: SNOW-470350 Deprecate Python 3.6

### PR DESCRIPTION
**Pull request by sfc-gh-jbahk**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes SNOW-470350

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

### CODE REVIEW

**Comment by sfc-gh-mkeller** [comment]
Has this been announced? When are we doing this again?
You'll also need to update: https://github.com/snowflakedb/snowflake-connector-python/blob/fc44a59b55948a1d7721bf8d9e40d3609f7e29a2/.github/workflows/build_test.yml#L31 https://github.com/snowflakedb/snowflake-connector-python/blob/fc44a59b55948a1d7721bf8d9e40d3609f7e29a2/.github/workflows/build_test.yml#L56 and there's still quite a few mentions of `3.6` in https://github.com/snowflakedb/snowflake-connector-python/blob/fc44a59b55948a1d7721bf8d9e40d3609f7e29a2/.github/workflows/build_test.yml

**Comment by sfc-gh-mkeller** [comment]
recheck

**Comment by sfc-gh-jbahk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sfc-gh-mkeller** [comment]
recheck

**Comment by sfc-gh-mkeller** [comment]
recheck

**Review by sfc-gh-mkeller — APPROVED** [review]

**Pull request merged**
