### PR TITLE
SNOW-220160 bump supported pandas version

### PR DESCRIPTION
**Pull request by sfc-gh-mkeller**
Opened for #439

### CODE REVIEW

**Comment by sid-kap** [comment]
Do you think this will be merged for the next release? Looks like some tests are failing because of skipped unit tests, but I can't tell if the issue is related to this change or just a flake

**Comment by sfc-gh-mkeller** [comment]
It's definitely flaky test. I have been trying to resolve this exact test over on my PR for a while.
I'll talk to my team, but I don't see why we couldn't!

Also @sid-kap you can always pull master and build the wheel yourself.

**Comment by sfc-gh-stakeda** [comment]
@sfc-gh-mkeller is this ready to merge?

**Comment by sfc-gh-mkeller** [comment]
Should be. Let me rebase it and re-run tests

**Review by sfc-gh-stakeda — APPROVED** [review]

**Comment by sid-kap** [comment]
Bump on this?

**Comment by sfc-gh-mkeller** [comment]
> Bump on this?

Just rebased and kicked off new tests! 🚀

**Pull request merged**
