### PR TITLE
Fix timeout log message

### LINKED ISSUE #1738: SNOW-923450: Misleading log message for query that times out
### Python version

Python 3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:01:19) [Clang 14.0.6 ]

### Operating system and processor architecture

macOS-12.6.7-arm64-arm-64bit

### Installed packages

```python
NA
```

### What did you do?

```python
Run a query with a short timeout and enable debug logging
```

### What did you expect to see?

A log message indicating that the timer fired and cancelled the query, however, the same log message is emitted whether the query timed out or not.

### Can you set logging to DEBUG and collect the logs?

```bash
import logging
import os

for logger_name in ('snowflake.connector',):
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

### PR DESCRIPTION
**Pull request by aneeshdurg**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #1738 1738

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [x] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   The debug message is more accurate and has a unique message depending on where the timer is being cancelled.

### CODE REVIEW

**Comment by aneeshdurg** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by aneeshdurg** [comment]
recheck

**Review by sfc-gh-stan — APPROVED** [review]

**Review by sfc-gh-sfan — APPROVED** [review]

**Comment by sfc-gh-sfan** [comment]
@aneeshdurg Can you create a new PR from a non-main branch? I think we are hitting this: https://github.com/orgs/community/discussions/65403

**Comment by aneeshdurg** [comment]
@sfc-gh-sfan , reopened as https://github.com/snowflakedb/snowflake-connector-python/pull/1753

**Pull request closed without merging**
