### PR TITLE
SNOW-297036 fix get_result_from_sfqid to enable pandas_fetch

### PR DESCRIPTION
**Pull request by dennis-wey**
Idea from https://github.com/snowflakedb/snowflake-connector-python/issues/647
Thanks to @javier5109 for finding this.

### CODE REVIEW

**Comment by dennis-wey** [comment]
@sfc-gh-kwagner @sfc-gh-mkeller @sfc-gh-cshi (since you are assigned to the issues)
According to the tests, it seems that all required tests ran through. Since this is my first pr for this project, is there anything left to do?

**Comment by sfc-gh-mkeller** [comment]
Hi @dennis-wey 
I'm sorry, but the tests are failing for me when I manually pull your changes and run the test that you changed.

```    def fetch_pandas_all(self, **kwargs):
        """Fetch Pandas dataframes in batches, where 'batch' refers to Snowflake Chunk."""
        self.check_can_use_pandas()
>       if self._query_result_format != "arrow":
E       AttributeError: 'SnowflakeCursor' object has no attribute '_query_result_format'

../../venv/lib64/python3.6/site-packages/snowflake/connector/cursor.py:853: AttributeError```

Since the cursor hasn't executed anything it's missing information about the results. I think a more straight forward way would be to identify what extra information would be necessary for `fetch_pandas*` to work and then copy those from the `inner_cursor` to the outer one.

What do you think about that approach?

**Comment by dennis-wey** [comment]
HI @sfc-gh-mkeller,
thanks for the feedback!
Yes sounds good, I will check and update the pr accordingly.

**Comment by dennis-wey** [comment]
@sfc-gh-mkeller  I've updated the pr. It seems like the problem was, that the `fetch_pandas` functions didn't trigger the prefetch_hook. I copied `_query_result_format` and `_total_rowcount` to the outer cursor since both are written by `_init_result_and_meta`. Overall is there a reason to rely on an inner cursor instead of relying on query_result or even execute in current cursor? Creating an internal cursor object and copy over protected variables seems prone to errors.

Also I'm currently not able to test the code myself, so I was hoping to rely on the github actions for that.

**Comment by dennis-wey** [comment]
Any comments @sfc-gh-mkeller?

**Comment by sfc-gh-mkeller** [comment]
Hey @dennis-wey 
I'm sorry for going MIA recently, things got a bot crazy lately.
Your PR looks good to me, you have really improved it! 👍 
I want to merge it. However, while I was looking through I found that there was `SnowflakeCursor._description` that wasn't copied properly from the internal cursor. I hope you don't mind I added this myself in the test (#737). If tests pass there then I'll be accepting your work through there.
Hope you have a good weekend and that we'll see your contribution again soon! 🎊 😄

**Comment by sfc-gh-mkeller** [comment]
Actually @dennis-wey it looks like there might be an issue with your git settings. If you look at your commits it doesn't look like they link to your account.
I want to give you a chance to fix this, so that your work would be linked to your name once it gets merged.
Please keep an eye on the tests running and let me know when you have fixed the issue. I'll wait with merging the PR until then! 😄

**Comment by dennis-wey** [comment]
Hi @sfc-gh-mkeller thanks for your feedback!

I rebased the pr here, so the commit should now link to my github account.

**Comment by sfc-gh-mkeller** [comment]
Merged through #737

**Pull request closed without merging**
