### PR TITLE
SNOW-200637 ease building conda packages

### PR DESCRIPTION
**Pull request by sfc-gh-mkeller**
Tests #418

### CODE REVIEW

**Comment by xhochy** [comment]
Mh, weird.

I manually downloaded the MacOS Python 3.8 wheel and I can import `snowflake.connector.arrow_result`. So I'm a bit confused why it seems in the test setup, the import fails.

**Comment by sfc-gh-mkeller** [comment]
The back-end seems to decide to not return Arrow format to the client and defaults to return JSON instead. I need to look into why this is.

**Comment by xhochy** [comment]
This is still failing as it cannot import `snowflake.connect.arrow_result` in the CI. I'm not a tox expert, @sfc-gh-mkeller do you have an idea where we could add `python -c 'import snowflake.connect.arrow_result'` in the tests to see what is the issue?

**Comment by xhochy** [comment]
🎉 looks like the issues are unrelated to my changes and most of CI is now green.

**Comment by sfc-gh-mkeller** [comment]
@xhochy would your PR be okay to merge like this? I just rebased it onto master

**Review by xhochy — APPROVED** [review]
Yes, that looks fine/nice.

**Review by sfc-gh-kwagner — APPROVED** [review]
LGTM

**Pull request merged**
