### PR TITLE
make a tzinfo class at the module level instead of inlining (fixes #81)

### LINKED ISSUE #81: TZ objects not pickleable
https://github.com/snowflakedb/snowflake-connector-python/blob/6c3e666ef6c388a3bde2b190256f88a615259196/converter.py#L155

Hello,

those dynamically-defined classes are not pickleable because they are not attached to the module:
```
PicklingError: Can't pickle <class 'snowflake.connector.converter.GMTN0400'>: attribute lookup snowflake.connector.converter.GMTN0400 failed
```

I wonder if we can cache them in the module's namespace so that they can be accessed and pickled.

### PR DESCRIPTION
**Pull request by beckjake**
Fixes #81 by creating a generic class with a name and an offset, and using instances of that for timezones.

I'm not clear on why snowflake uses `type` inline to create a fresh class for each timezone, but it breaks picking of results, which is very annoying and means we have to wrap all results with code that does basically this if we want to pickle anything.

This pattern comes straight from the python docs, check out the "FixedOffset" class defined [on this page](https://docs.python.org/2/library/datetime.html#datetime.datetime.tzinfo)

### CODE REVIEW

**Comment by drewbanin** [comment]
Is anyone able to take a look at this one?

**Comment by smtakeda** [comment]
no worry, this is in the queue.

**Comment by smtakeda** [comment]
Writing a test case:
```
def test_pickle_timestamp_tz(tmpdir, conn_cnx):
    tmp_dir = str(tmpdir.mkdir('pickles'))
    output = os.path.join(tmp_dir, 'tz.pickle')
    expected_tz = None
    with conn_cnx() as con:
        for rec in con.cursor().execute("select '2019-08-11 01:02:03.123 -03:00'::TIMESTAMP_TZ"):
            expected_tz = rec[0]
            with open(output, 'wb') as f:
                pickle.dump(expected_tz, f)
                print(expected_tz)
                print(type(expected_tz))

    with open(output, 'rb') as f:
        read_tz = pickle.load(f)
        print(read_tz)
        assert expected_tz == read_tz
```
But got this error:
```
>           read_tz = pickle.load(f)
E           TypeError: __init__() missing 2 required positional arguments: 'name' and 'tzoffset_minutes'
```

**Comment by smtakeda** [comment]
This looks like working well.
https://github.com/stub42/pytz/blob/master/src/pytz/__init__.py#L391
```
pytz.FixedOffset
```

**Comment by smtakeda** [comment]
@beckjake and @drewbanin can you review #191 ?

**Comment by drewbanin** [comment]
Hey @smtakeda - this looks really great! I didn't know about `pytz.FixedOffset`. I gave this patch a spin locally and it appears to work really well :)

**Comment by smtakeda** [comment]
working on other branch.

**Pull request closed without merging**
