### PR TITLE
Remove dependencies on Cryptodome and oscrypto

### LINKED ISSUE #1605: SNOW-843716: Cryptography library cleanup
### What is the current behavior?

Hi! It looks like the connector depends on five cryptography-related packages, `asn1crypto`, `cryptography`, `oscrypto`, `pyOpenSSL`, and `pycryptodome`.

Would there be interest in consolidating these as far as possible? I think most of this can be consolidated onto just the cryptography library. I'd be happy to contribute a pull request, just wanted to check with you all first. The one I'm least sure about is `asn1crypto`, but it looks like that one's being used for OCSP support, which `cryptography` has high-level functions for. From a quick look, everything else seems like stuff I'm pretty sure `cryptography` can handle.

### What is the desired behavior?

Ideally, the connector should depend on a single, well-maintained cryptography library.

### How would this improve `snowflake-connector-python`?

This would reduce maintenance overhead and security risk.

### References and other background

_No response_

### PR DESCRIPTION
**Pull request by geofft**
The code to use cryptography (which uses OpenSSL) already existed, but it just wasn't being used by default. Since cryptography is currently a mandatory dependency, we may as well use it all the time.

Partially resolves #1605/SNOW-843716.

### CODE REVIEW

**Comment by geofft** [comment]
1. Can you please document the need for CLAs in CONTRIBUTING.md? I checked before volunteering to contribute. Getting a CLA process is an internally onerous process and I prefer not to contribute to repositories that require it.
2. The CLA link gives me a 404, so I am unable to do anything with it.

**Comment by kpark-hrp** [comment]
@geofft @sfc-gh-sfan Are there plans to merge this in any time soon? Getting `oscrypto` would be very helpful

**Review by kpark-hrp — APPROVED** [review]

**Comment by kpark-hrp** [comment]
@sfc-gh-sfan It looks like it's failing on linters

**Comment by sfc-gh-sfan** [comment]
@geofft Can you fix the linter error?

**Comment by kpark-hrp** [comment]
> @geofft Can you fix the linter error?

Just a reminder 😃

**Comment by sfc-gh-sfan** [comment]
test PR in https://github.com/snowflakedb/snowflake-connector-python/pull/1752

**Comment by sfc-gh-sfan** [comment]
@geofft Can you sign the CLA (link: https://github.com/snowflakedb/CLA/blob/main/README.md)?

**Comment by kpark-hrp** [comment]
Hey @geofft, can this be driven to completion?

**Comment by sfc-gh-sfan** [comment]
Done in https://github.com/snowflakedb/snowflake-connector-python/pull/1779

**Pull request closed without merging**
