### PR TITLE
Second attempt at fixing the diagnostics issues

### PR DESCRIPTION
**Pull request by sfc-gh-cconner**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

Fixes issues with the connection diagnostic failing to check OCSP and stages.

2. Fill out the following pre-review checklist:

   - [x ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

Connection diagnostics were failing because of the result on OCSP checks.  Fixed this to decrypt the byte responses.

### CODE REVIEW

**Comment by sfc-gh-cconner** [comment]
I had to rebase my other branch and it just got really messed up and seemed easier to do a different branch.

**Review by sfc-gh-sfan — COMMENTED** [review]
Is there an example of decoded string?

**Comment by sfc-gh-sfan** [comment]
Test PR: https://github.com/snowflakedb/snowflake-connector-python/pull/1757

**Comment by sfc-gh-cconner** [comment]
> Is there an example of decoded string?

I added a test for the decoded string and a test of the https_host_check method that was failing before we added this.

**Review by sfc-gh-sfan — APPROVED** [review]

**Comment by sfc-gh-sfan** [comment]
@sfc-gh-cconner : Looks like the merge gates are green, but currently the main branch is locked until nanoarrow PR is in. Once main is unlocked, we could get your changes in

**Pull request merged**
