### PR TITLE
SNOW-743085 remove pandas concat kwargs(fetch_pandas_all)

### PR DESCRIPTION
**Pull request by hosimesi**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #1430 (SNOW-743085)

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

### CODE REVIEW

**Comment by sfc-gh-stan** [comment]
Hello @hosimesi , thank you submitting a PR to address this issue. I looked at the historical changes, you are right about the cause. For versions before `2.4.1`, we pass `kwargs` to [pyArrow.Table.to_pandas](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.to_pandas), but when we introduced parallel fetch in #787 , `_fetch_pandas_all` mistakenly passes `kwargs` to pandas.concat` instead. 
To be fully honest, I'm not sure what the best thing to do is here because neither of these are documented behaviors and therefore should not be relied on. I'm leaning towards accepting your change and restore the old behavior, but I will have to discuss this with the other maintainers before making the final decision.
Meanwhile, please feel free to sign the CLA and mark the PR as review ready. Thank you for your contribution!

**Comment by hosimesi** [comment]
Hello @sfc-gh-stan 
Sorry for the late reply.
I Understood and thank you for your quick response.

**Comment by hosimesi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hosimesi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hosimesi** [comment]
@sfc-gh-stan 
Hi! 
What is going on with this case?

**Review by sfc-gh-sfan — COMMENTED** [review]
@sfc-gh-mkeller : Could you chime in and see if the original is intentional?

**Comment by sfc-gh-mkeller** [comment]
> Could you chime in and see if the original is intentional?
The original was a mistake.

However; this PR has been superseded/implemented by https://github.com/snowflakedb/snowflake-connector-python/pull/1649 recently

**Pull request closed without merging**
