### PR TITLE
SNOW-544967: Print URL when trying browser authentication

### LINKED ISSUE #1064: SNOW-544967: URL should be printed in terminal during browser authentication
## What is the current behavior?
During browser authentication with my identifty provider, there is sometimes no browser window. I have no option but to rerun the dbt run, which can take time.

## What is the desired behavior?
Show the URL so the user can click it during the run.

### PR DESCRIPTION
**Pull request by thomasaarholt**
- Clarify that Ctrl + C only aborts and doesnt retry
- Print authentication link, in case browser window fails to appear

Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.
Fixes #1064

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [x] I am adding new logging messages
   - [ ] I am modifying authorization mechanisms
   - [ ] I am adding new credentials
   - [ ] I am modifying OCSP code
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

The URL is now shown, so that the user can click it if the browser is opened.

Also added a comma to the "try again" sentence, since Ctrl + C does not retry the run for the user.

### CODE REVIEW

**Comment by thomasaarholt** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by thomasaarholt** [comment]
recheck

**Review by turbaszek — APPROVED** [review]
Looks reasonable to me 👌

**Comment by nicholasgibson2** [comment]
@sfc-gh-mkeller @sfc-gh-kwagner @sfc-gh-jbahk would one of you guys mind reviewing this? My team would love to see this feature 😃

**Pull request closed without merging**
