### PR TITLE
SNOW-216307 Make PUT statements threadsafe

### PR DESCRIPTION
**Pull request by jameskrach**
The [documentation](https://docs.snowflake.com/en/user-guide/python-connector-api.html#threadsafety) indicates that the connection can be shared by threads, but by using the [default boto3 session](https://github.com/snowflakedb/snowflake-connector-python/blob/14c96fbc279eca5a1440be927f5095dae8d50322/src/snowflake/connector/s3_util.py#L75), PUT statements are not threadsafe.

I believe this to be the cause of #156. Further docs of the non-threadsafety of boto3 can be seen [here](https://github.com/boto/botocore/issues/1246).

This PR simply creates a `boto3.Session` within `snowflake.connector.s3_util.SnowflakeS3Util.create_client()`. This will prevent multiple threads that share a `snowflake.connector.Connection` object from attempting to unsafely share the default boto3 connection when running a statement like `.execute("PUT ...")`.

### CODE REVIEW

**Comment by jameskrach** [comment]
Any thoughts or questions on this? I’m happy to be helpful in getting this resolved however I can.

**Comment by sfc-gh-mkeller** [comment]
No, sorry @jameskrach I just haven't gotten around to read all of the documentation yet.
I promise I'll get around to early next week.

**Comment by sfc-gh-mkeller** [comment]
Hi @jameskrach right here in the docs boto3 says that sessions are not thread safe https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html#multithreading-and-multiprocessing
Are you sure that your code would make AWS PUTs thread safe here?

**Comment by jameskrach** [comment]
I believe the `.create_client()` method is called by the connector whenever a `PUT` statement gets executed. So if the method is called within a thread (e.g. by a thread that's sharing a connection), and the session creation happens within the thread, then there shouldn't be any sharing of the session across threads.

I haven't run this (I can try it out tomorrow), but a a minimum example should look something like the code below. eventually that while loop should raise some kind of boto error (it might require adjusting the rowcount/number of concurrent uploads)

```
from concurrent.futures import ThreadPoolExecutor

import pandas as pd
from snowflake.connector import connect
from snowflake.connector.pandas_tools import write_pandas


kwargs = {...}
df = pd.DataFrame({"A": range(500), "B": range(500, 1000)})
tbl_nm = "bug_example"
uploads_at_a_time = 10


with connect(**kwargs) as conn, ThreadPoolExecutor(max_workers=5) as tp:
    with conn.cursor() as cur:
        _ = cur.execute(f"CREATE TABLE {tbl_nm} (a NUMBER, b NUMBER)")

    f = lambda n: write_pandas(conn, df, tbl_nm.upper(), parallel=1)
    results = []

    while True:
        results.append(tp.map(f, range(uploads_at_a_time)))
        print(results[-uploads_at_a_time:])
```

**Comment by sfc-gh-mkeller** [comment]
I think the proper way to do this would be to return the Session as the client and then each worker thread could create their own Resource from that.

Does that sound like the proper way to fix the concurrency issue?

**Comment by sfc-gh-stakeda** [comment]
According to https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html#multithreading-and-multiprocessing, each thread needs its own `session` as well as `resource`. So it msees the main thread should pass the credentials to the downloader threads to get authenticated individually.

**Comment by jameskrach** [comment]
The docs are a bit ambiguous about whether or not sessions are threadsafe, but resources certainly aren’t.

Since (I assume) most PUT operations spend a fairly large amount of time uploading data relative to how long it takes to create a session, I’d imagine @sfc-gh-stakeda’s suggestion of creating a session as well is a good one

**Comment by sfc-gh-stakeda** [comment]
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/session.html#multithreading-or-multiprocessing-with-sessions
> Similar to Resource objects, Session objects are not thread safe and should not be shared across threads and processes.

I imagine the session is stateful that impacts a series of function calls.

**Comment by sfc-gh-mkeller** [comment]
I guess I'll take over this ticket, unless you'd really like to implement this @jameskrach

**Comment by jameskrach** [comment]
Seeing as how I missed the right spot to implement the change on the first go round I think I’d leave it to you

**Comment by sfc-gh-mkeller** [comment]
Thank you for bringing this to our attention, @jameskrach

**Pull request closed without merging**
