### PR TITLE
Make AWS & Azure optional dependencies

### LINKED ISSUE #124: Optional dependencies for azure and boto?
As user not intending to use boto or azure modules, e.g. in case of using the connector for simple queries to Snowflake, is it be possible to relax the dependency requirements for these particular modules?

### PR DESCRIPTION
**Pull request by borgstrom**
**This is still WIP**

This PR builds upon #172 and aims to make AWS & Azure optional dependencies that must be installed via setuptools “extras”.

TODO:

* [ ] Update documentation with instructions on how to install the optional dependencies

Closes #172 
Closes #124

### CODE REVIEW

**Comment by borgstrom** [comment]
I can’t run the tests locally since I don’t really understand what is supposed to be in the `parameters.py` file and [since PRs from forks can’t access secrets](https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions) I can’t get any feedback from Travis & Appveyor.

We’re testing this locally to validate the changes.

**Comment by smtakeda** [comment]
Thanks for PR. This duplicates #124.
This change is in the JIRA queue finding the right timing.

**Comment by borgstrom** [comment]
Thanks for replying. 

My read of your comment is that you’re not open to considering my changes and would rather make the changes yourself.  Is that correct?

Considering #124 has been opened for 9 months, how can we influence the timing?  Should we ask our account contacts at snowflake to escalate this issue internally?

We do not use azure services. The azure libraries declare namespaces using PEP420 and we use pkg_resources style namespaces already, and since the two are not compatible and we are forced to pickup the azure libraries via this one it is currently blocking our efforts to get into production on snowflake. 

P.S. This can’t duplicate #124.  That is an issue. This is a PR.  It can only fix #124.

**Comment by smtakeda** [comment]
Timing wise, as another cloud support is coming up, we are re-thinking of packaging anyway.

Please feel free to reach out the customer support to escalate the issue. It would be helpful to have more customer requests for PM to set priorities.

**Comment by smtakeda** [comment]
Duplicates #124

**Comment by sburns** [comment]
We're now at 16 months for #124. Whatever y'all are doing internally, we're still sitting here installing azure stuff into all of our lambdas and containers running on ECS.

This is fine.

**Comment by keller00** [comment]
Hi @sburns 
I'm sorry for the delay.
Note that I'm working on this change and it will be released soon, but we have been going through a massive testing overhaul recently and that now we have an easier way to test different optional dependency installations.
So rest be assured this change has been in the works for months now.

**Comment by sburns** [comment]
@keller00 this is great news indeed. It's obviously hard for us on the outside to know internal roadmaps so any updates you can provide are welcome. I'm sure you'll find some willing participants in this thread to help test when the time comes :)

**Pull request closed without merging**
